### ISSUE TITLE
可以整一个阅读源转eso源的工具，这样能够大大增加eso源的数量

### ISSUE THREAD

**Issue by woodwen** [mabDc/eso_source#10]

**Comment by mabDc** [comment]
你好。阅读2字段比较相近，阅读3改动太多，还是要自己调试和修改的。工具只能解析了帮助对号填入。写规则建议用pc端哦。可能写的更快。

**Comment by woodwen** [comment]
那或者把源解析这块拆解出来，然后尽量往 阅读3靠，背靠大树好乘凉，阅读3的源 太充足了，这样的话 再写工具也方便

**Comment by mabDc** [comment]
并无比打算。因为它是它。亦搜支持zy-player，如果你有兴趣
